### ISSUE TITLE
Error: Can't walk dependency graph: Cannot find module

### ISSUE THREAD

**Issue by rk508501** [bahmutov/cypress-await#32]
Getting error below upon installation of the plugin:

Error: Can't walk dependency graph: Cannot find module './commands' from '/private/var/folders/tm/l34rvdd51w7fkc13jcsxqy3h0000gn/T/1ae96f0f-32e0-4948-90aa-cc50ffda2eae/e2e.js.js'
    required by /private/var/folders/tm/l34rvdd51w7fkc13jcsxqy3h0000gn/T/1ae96f0f-32e0-4948-90aa-cc50ffda2eae/e2e.js.js
    at /Users/garu/Downloads/Automation/node_modules/resolve/lib/async.js:167:35
    at load (/Users/garu/Downloads/Automation/node_modules/resolve/lib/async.js:186:43)
    at onex (/Users/garu/Downloads/Automation/node_modules/resolve/lib/async.js:211:17)
    at /Users/garu/Downloads/Automation/node_modules/resolve/lib/async.js:24:69
    at callback (/Users/garu/Library/Caches/Cypress/13.3.2/Cypress.app/Contents/Resources/app/packages/server/node_modules/graceful-fs/polyfills.js:299:20)
    at callback (/Users/garu/Library/Caches/Cypress/13.3.2/Cypress.app/Contents/Resources/app/packages/server/node_modules/graceful-fs/polyfills.js:299:20)
    at FSReqCallback.oncomplete (node:fs:210:21)

My Package.json
`{
  "name": "automation",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "npx cypress open"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "cypress": "^13.3.2",
    "dayjs": "^1.11.9"
  },
  "devDependencies": {
    "cypress-await": "^1.4.4"
  }
}`

My config:
`const { defineConfig } = require("cypress");
// https://github.com/bahmutov/cypress-await
const cyAwaitPreprocessor = require('cypress-await/src/preprocessor')

module.exports = defineConfig({
  e2e: {
    testIsolation:false,
    setupNodeEvents(on, config) {
      // implement node event listeners here
      on('file:preprocessor', cyAwaitPreprocessor())
    },
  },
});`

My Spec:
`describe("Test", ()=>{
    it('shows the number of projects', async () => {
        await cy.visit('https://github.com/bahmutov/cypress-await')
        const n = await cy.get('#repository-container-header').invoke('text')
        cy.log(n)
      })
})`

**Comment by rkumarkundu** [comment]
same issue in my system 

Error: Can't walk dependency graph: Cannot find module './commands' from 'C:\Users\RANJIT~1\AppData\Local\Temp\99b485ac-7b73-4f63-af21-889e127d18ef\e2e.js.js'
    required by C:\Users\RANJIT~1\AppData\Local\Temp\99b485ac-7b73-4f63-af21-889e127d18ef\e2e.js.js
    at C:\project\RnD\node_modules\resolve\lib\async.js:167:35
    at load (C:\project\RnD\node_modules\resolve\lib\async.js:186:43)
    at onex (C:\project\RnD\node_modules\resolve\lib\async.js:211:17)
    at C:\project\RnD\node_modules\resolve\lib\async.js:24:69
    at callback (C:\Users\RanjitKundu\AppData\Local\Cypress\Cache\13.3.3\Cypress\resources\app\node_modules\@packages\server\node_modules\graceful-fs\polyfills.js:299:20)
    at callback (C:\Users\RanjitKundu\AppData\Local\Cypress\Cache\13.3.3\Cypress\resources\app\node_modules\@packages\server\node_modules\graceful-fs\polyfills.js:299:20)
    at FSReqCallback.oncomplete (node:fs:210:21)

**Comment by SuperJessiK** [comment]
I am also encountering the same problem. Can you please give an idea of when it will be fixed?

**Comment by bahmutov** [comment]
I'm sorry I do not have time to work on this, but if someone opens a pull request with an update, I will be happy to review and merge it

**Comment by SuperJessiK** [comment]
Thanks for your reply. That's quite a shame. But if you do merge some code,
please let me know. TIA
Yael

**Comment by vesper8** [comment]
Same here.. why is this suddenly happening? Was this plugin working fine and then Cypress got updated and now it's not working anymore?

**Comment by J7mbo** [comment]
This is not resolved since October so I understand that the library is not being maintained any more, does anyone have an alternative, a fix, or want to build one?

**Comment by bahmutov** [comment]
Please, if this is a blocker for you, provide a reproducible simple example plus open a pull request to fix this.
